### ISSUE TITLE
dhcpd.conf mapping

### ISSUE THREAD

**Issue by cwong-archy** [sdelrio/rpi-hostap#19]
is this repo still being developed? or these issues still being monitored?

wondering if we can map the dhcpd.conf file via `volumes:` instead of hardcoding in the startup script -
```
echo "Configuring DHCP server .."

cat > "/etc/dhcpd.conf" <<EOF
option domain-name-servers ${PRI_DNS}, ${SEC_DNS};
option subnet-mask 255.255.255.0;
option routers ${AP_ADDR};
subnet ${SUBNET} netmask 255.255.255.0 {
  range ${SUBNET::-1}100 ${SUBNET::-1}200;
}
EOF
```

i would like to do this -
```
    volumes:
      - './isc-dhcp-server/etc-dhcp/dhcpd.conf:/etc/dhcpd.conf'
```

**Comment by cwong-archy** [comment]
i tested it out locally and it works -
```
-cat > "/etc/dhcpd.conf" <<EOF
+if [[ ! -f /etc/dhcpd.conf ]]; then
+    cat > "/etc/dhcpd.conf" <<EOF
 option domain-name-servers ${PRI_DNS}, ${SEC_DNS};
 option subnet-mask 255.255.255.0;
 option routers ${AP_ADDR};
@@ -111,9 +112,10 @@ subnet ${SUBNET} netmask 255.255.255.0 {
   range ${SUBNET::-1}100 ${SUBNET::-1}200;
 }
 EOF
+fi
```

with my docker-compose.yml -
```
---
version: '3.8'

services:
  hostap:
    build: ./rpi-hostap
    container_name: hostap
    # image: sdelrio/rpi-hostap:latest
...
```
